#!/bin/sh
# This code is publish under GPLv3 or later verions. See COPYING file
# ~Aeredren (Romain Lebrun Thauront <romain.lebrun-thauront at protonmail.com>)

lister () {
	[ $LIST -eq 0 ] && printf "../\n./\n$(ls -p .)" || echo "$(ls -ap .)"
}


command_input () {
	cd $1
	INPUT="$(lister | dmenu -nf "red" -sb "red" -b -i)"
	case $INPUT in
		"\\")
			dmenu_explorer $DIR $LIST &
			;;
		":")
			command_input /usr/bin &
			;;
		".")
			[ $LIST -eq 0 ] && LIST=1 || LIST=0
			command_input $PWD &
			;;
		*)
			[ -d "$INPUT" ] && command_input "$INPUT" || (COMMAND="$INPUT" ; arg_input $DIR)
			;;
	esac
}

arg_input () {
	cd $1
	BUFFER="$(lister | dmenu -nf "blue" -sb "blue" -b -i | sed -e :a -e '$!N;s/ *\n */ /;ta' -e 'P;D')"
	INPUT=${BUFFER##* }
	ARGUMENTS="$ARGUMENTS $(realpath ${BUFFER%$INPUT})"

	#echo "BUFFER IS : $BUFFER"
	#echo "INPUT IS : $INPUT"
	#echo "ARGUMENTS IS : $ARGUMENTS"
	#echo
	
	case $INPUT in
		"\\")
			dmenu_explorer $PWD $LIST &
			;;
		":")
			unset BUFFER
			unset INPUT
			unset ARGUMENTS
			command_input /usr/bin &
			;;
		".")
			[ $LIST -eq 0 ] && LIST=1 || LIST=0
			arg_input $PWD
			;;
		"./")
			ARGUMENTS="$ARGUMENTS $INPUT" ; [ -z $COMMAND ] || "$COMMAND $ARGUMENTS"
			;;
		*)
			[ -d "$INPUT" ] && arg_input "$INPUT" || (ARGUMENTS="$ARGUMENTS $INPUT" ; [ -z $COMMAND ] || $COMMAND $ARGUMENTS)
			;;
	esac
	
}

[ -z $1 ] && DIR=$HOME || DIR=$1
[ -z $2 ] && LIST=0 || LIST=$2
command_input /usr/bin

