#!/bin/sh
# This code is publish under GPLv3 or later verions. See COPYING file
# ~Aeredren (Romain Lebrun Thauront <romain.lebrun-thauront at protonmail.com>)

lister () {
	[ $LIST -eq 0 ] && printf "../\n./\n$(ls -p .)" || echo "$(ls -ap .)"
}


explore () {
	cd $1
	BUFFER="$(lister | dmenu -b -i | sed -e :a -e '$!N;s/ *\n */ /;ta' -e 'P;D')"
	INPUT=${BUFFER##* }
	ARGUMENTS="$ARGUMENTS $(realpath ${BUFFER%$INPUT})"

	case $INPUT in
		"")
			exit 0
			;;
		"\\")
			explore $HOME $LIST &
			;;
		":")
			unset BUFFER
			unset INPUT
			unset ARGUMENTS
			dmenu_explorer_command $PWD $LIST &
			;;
		".")
			[ $LIST -eq 0 ] && LIST=1 || LIST=0
			explore $PWD
			;;
		"./")
			open "$ARGUMENTS $INPUT"
			;;
		*)
			[ -d "$INPUT" ] && explore "$INPUT" || open $INPUT $ARGUMENTS
			;;
	esac
	
}

open () {
	for FILE in $@; do
		xdg-open "$FILE" & >> /dev/null 
	done
	explore $PWD $LIST &
}

[ -z $2 ] && LIST=0 || LIST=$2
[ -z $1 ] && explore $HOME || explore $1
